name: Build and tag

on:
  push:
    branches:
      - main
    tags:
      - '!*'

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: |
          npm run build

      - name: Get version
        uses: bbonkr/get-version-action@v1
        id: get_version
        with:
          project: package.json

      - name: check tag exists
        uses: bbonkr/git-tag-check-action@v1.0.18
        id: check_tag
        with:
          tag: 'v${{ steps.get_version.outputs.version }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: package-version-to-git-tag
        uses: pkgdeps/git-tag-action@v2
        if: ${{ steps.check_tag.outputs.tag == '' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ steps.get_version.outputs.version }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: 'v'
