name: Deployment

on:
  release:
    types: [published]

jobs:
  deployment:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: |
          npm run build
        env:
          NODE_ENV: production

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
