name: Verify PR

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  verify-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: |
          npm run build
